name: Build TTN-Bridge

on: [push]

jobs:
  build:
    name: Build pack and release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout parent project with dependencys
      uses: actions/checkout@v1
      with:
        repository: MONICA-Project/ttn-bridge-project
        ref: refs/heads/master
        submodules: true

    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        
    - name: Witch dir 1
      run: |
        ls
        pwd
        echo $(pwd)
      shell: bash
      
    - name: Witch dir 1
      run: |
        ls
        pwd
        echo $(pwd)
      working-directory: ../ttn-bridge-project/TTN-Bridge
      shell: bash

    - name: Build with dotnet
      run: dotnet build TTN-Bridge_Core.sln --configuration Release
      working-directory: ./TTN-Bridge

    - name: Create deb files
      run: |
        mkdir ../../../Builds 
        chmod oug+x make-deb-core.sh 
        ./make-deb-core.sh amd64 
        ./make-deb-core.sh armhf
      working-directory: ./TTN-Bridge/TTN-Bridge/dpkg
      shell: bash
